bishop/bishop/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import product_by_category_view
from webapp.views.views import IndexViews, ProductView, ProductCreate, ProductUpdate, ProductDelete

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexViews.as_view(), name='index'),
    path('product/<int:pk>/view/', ProductView.as_view(), name='product_view'),
    path('product/<int:pk>/update/', ProductUpdate.as_view(), name='product_update'),
    path('product/<int:pk>/delete/', ProductDelete.as_view(), name='product_delete'),
    path('product/add/', ProductCreate.as_view(), name='product_add'),
    path('product/<str:category>/', product_by_category_view, name='product_by_category'),

]

bishop/webapp/models.py
from django.db import models

CATEGORIES_CHOICES = [("other", "Разное"), ("electronics", "Электроника"), ("books", "Книги"),
                      ("stationery", "Канцтовары")]


# Create your models here.
class Product(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False, verbose_name='Наименование товара')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='Описание товара')
    category = models.CharField(max_length=50, choices=CATEGORIES_CHOICES, default=CATEGORIES_CHOICES[0][0],
                                verbose_name="Категория")
    balance = models.PositiveIntegerField(verbose_name='Остаток')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name="Стоимость")

    def __str__(self):
        return f'{self.id}. {self.name}'

class Basket(models.Model):
    product = models.ForeignKey('webapp.Product', related_name='products', on_delete=models.CASCADE, verbose_name='Продукт')
    quantity = models.IntegerField()

    def __str__(self):
        return f'{self.id}. {self.product}'

bishop/webapp/forms.py
from django import forms
from django.forms import widgets
from webapp.models import CATEGORIES_CHOICES, Product


class SearchForm(forms.Form):
    search = forms.CharField(max_length=50, required=False, label="Найти")


class ProductForm(forms.Form):
    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'balance', 'price']
        exclude = ['balance']
    # name = forms.CharField(max_length=100, required=True, label='Наименование товара')
    # description = forms.CharField(max_length=2000, required=False, label='Описание товара', widget=widgets.Textarea)
    # category = forms.ChoiceField(choices=CATEGORIES_CHOICES, label='Категория')
    # balance = forms.IntegerField(min_value=0, required=True, label='Остаток')
    # price = forms.DecimalField(max_digits=7, decimal_places=2, label='Стоимость')

bishop/webapp/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, View
from django.db.models import Q
from django.utils.http import urlencode

class SearchView(ListView):
    search_form_class = None
    search_form_field = 'search'
    query_name = 'query'
    search_fields = []

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_search_form(self):
        if self.search_form_class:
            return self.search_form_class(self.request.GET)

    def get_search_value(self):
        if self.form:
            if self.form.is_valid():
                return self.form.cleaned_data[self.search_form_field]

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(self.get_query())
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        if self.form:
            context['form'] = self.form
            if self.search_value:
                context[self.query_name] = urlencode({self.search_form_field: self.search_value})
                context[self.search_form_field] = self.search_value
        return context

    def get_query(self):
        query = Q()
        for field in self.search_fields:
            kwargs = {field: self.search_value}
            query = query | Q(**kwargs)
        return query

class DeleteView(View):
    template_name = None
    confirm_deletion = True
    model = None
    key_kwarg = 'pk'
    context_key = 'object'
    redirect_url = ''

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.confirm_deletion:
            return render(request, self.template_name, self.get_context_data())
        else:
            self.perform_delete()
            return redirect(self.get_redirect_url())

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.perform_delete()
        return redirect(self.get_redirect_url())

    def perform_delete(self):
        self.object.delete()

    def get_context_data(self, **kwargs):
        return {self.context_key: self.object}

    def get_object(self):
        pk = self.kwargs.get(self.key_kwarg)
        return get_object_or_404(self.model, pk=pk)

    def get_redirect_url(self):
        return self.redirect_url

class UpdateView(View):
   form_class = None
   template_name = None
   redirect_url = ''
   model = None
   key_kwarg = 'pk'
   context_key = 'object'

   def get(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object)
       context = self.get_context_data(form=form)
       return render(request, self.template_name, context=context)

   def post(self, request, *args, **kwargs):
       self.object = self.get_object()
       form = self.form_class(instance=self.object, data=request.POST)
       if form.is_valid():
           return self.form_valid(form)
       else:
           return self.form_invalid(form)

   def form_valid(self, form):
       self.object = form.save()
       return redirect(self.get_redirect_url())

   def form_invalid(self, form):
       context = self.get_context_data(form=form)
       return render(self.request, self.template_name, context=context)

   def get_object(self):
       pk = self.kwargs.get(self.key_kwarg)
       return get_object_or_404(self.model, pk=pk)

   def get_context_data(self, **my_kwargs):
       context = self.kwargs.copy()
       context[self.context_key] = self.object
       context.update(my_kwargs)
       return context

   def get_redirect_url(self):
       return self.redirect_url

bishop/webapp/views/views.py
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView

from webapp.models import Product, CATEGORIES_CHOICES
from webapp.forms import SearchForm, ProductForm
from webapp.views.base_views import SearchView, UpdateView, DeleteView


# Create your views here.

class IndexViews(SearchView):
    template_name = 'product/index.html'
    context_object_name = 'tasks'
    model = Product
    # ordering = ('-updated_at',)
    paginate_by = 10
    paginate_orphans = 2
    search_form_class = SearchForm
    search_fields = ['name__icontains', 'description__icontains']

    def post(self, request, *args, **kwargs):
        for task_pk in request.POST.getlist('tasks', []):
            self.model.objects.get(pk=task_pk).delete()
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

# def index_view(request):
#     products = Product.objects.filter(balance__gt=0).order_by('category', 'name')
#     form = ProductForm()
#     search_form = SearchForm(data=request.GET)
#     if search_form.is_valid():
#         name = search_form.cleaned_data['search']
#         if name:
#             products = products.filter(name=name)
#             # products = products.filter(name__icontains=name)
#
#     return render(request, 'product/index.html',
#                   {'products': products, 'form': form, 'search_form': search_form, 'categories': CATEGORIES_CHOICES})



class ProductView(DetailView):
    template_name = 'product/product_by_category.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['task'] = get_object_or_404(Product, pk=self.kwargs.get('pk'))
        return context

def product_by_category_view(request, category, ):
    products = Product.objects.filter(balance__gt=0, category=category).order_by('name')
    form = ProductForm()
    search_form = SearchForm(data=request.GET)
    if search_form.is_valid():
        name = search_form.cleaned_data['search']
        if name:
            products = products.filter(name=name)
            # products = products.filter(name__icontains=name)
    try:
        name_category = dict(CATEGORIES_CHOICES)[category]
    except KeyError:
        raise Http404()
    return render(request, 'product/product_by_category.html',
                  {'products': products, 'form': form, 'search_form': search_form, 'category': name_category})


# def product_view(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     return render(request, 'product/product_view.html', {'product': product})


class ProductCreate(CreateView):
    template_name = 'product/product_by_category.html'
    model = Product
    form_class = ProductForm


# def product_create_view(request):
#     if request.method == "POST":
#         form = ProductForm(data=request.POST)
#         if form.is_valid():
#             product = Product.objects.create(**form.cleaned_data)
#             return redirect('product_view', pk=product.pk)
#         else:
#             products = Product.objects.filter(balance__gt=0).order_by('category', 'name')
#             search_form = SearchForm(data=request.GET)
#             if search_form.is_valid():
#                 name = search_form.cleaned_data['search']
#                 if name:
#                     products = products.filter(name=name)
#             return render(request, 'product/index.html', {'products': products, 'form': form, 'search_form': search_form,
#                                                   'categories': CATEGORIES_CHOICES})


class ProductUpdate(UpdateView):
    form_class = ProductForm
    template_name = 'product/product_create.html'
    model = Product
    product = None
    context_object_name = 'product'
    redirect_url = 'index'


# def product_update_view(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == "GET":
#         form = ProductForm(initial={
#             'name': product.name,
#             'description': product.description,
#             'category': product.category,
#             'balance': product.balance,
#             'price': product.price,
#         })
#         return render(request, 'product_create.html', {'form': form, 'product': product})
#     elif request.method == "POST":
#         form = ProductForm(data=request.POST)
#         if form.is_valid():
#             product.name = form.cleaned_data['name']
#             product.description = form.cleaned_data['description']
#             product.category = form.cleaned_data['category']
#             product.balance = form.cleaned_data['balance']
#             product.price = form.cleaned_data['price']
#             product.save()
#             return redirect('product_view', pk=product.pk)
#         return render(request, 'product/product_update.html', {'form': form})

class ProductDelete(DeleteView):
    template_name = 'product/product_delete.html'
    model = Product
    context_key = 'product'
    redirect_url = reverse_lazy('index')


# def product_delete_view(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == "GET":
#         return render(request, 'product/product_delete.html', {'product': product})
#     elif request.method == "POST":
#         product.delete()
#         return redirect('index')

bishop/webapp/templates/product/index.html
{% extends 'base.html' %}

{% block nav %}
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Категории
    </a>
    <ul class="dropdown-menu">
        {% for key, category in categories %}
            <li><a class="dropdown-item" href="{% url 'product_by_category' key %}">{{ category }}</a></li>
        {% endfor %}
    </ul>
    <form class="d-flex" role="search">
        {{ search_form.search }}
        <button class="btn btn-outline-success ms-2" type="submit">Найти</button>
    </form>
{% endblock %}


{% block content %}
    <h1>Список товаров</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'product_add' %}" method="POST">
                {% include 'partial/product_form.html' with button_text='Создать' %}
            </form>
        </div>
    </div>
    {% if is_paginated %}
        {% include 'partial/pagination.html' %}
    {% endif %}
    {% include "partial/product_list.html" %}

{% endblock %}

bishop/webapp/templates/product/product_by_category.html
{% extends 'base.html' %}

{% block nav %}
    <form class="d-flex" role="search">
        {{ search_form.search }}
      <button class="btn btn-outline-success ms-2" type="submit">Найти</button>
    </form>
{% endblock %}


{% block content %}
    <h1>{{ category }}</h1>
    <div class="card">
        <div class="card-body">
            <form action="{% url 'product_add' %}" method="POST">
                {% include 'partial/product_form.html' with button_text='Создать' %}
            </form>
        </div>
    </div>
    {% include "partial/product_list.html" %}
{% endblock %}

bishop/webapp/templates/product/product_delete.html
{% extends 'base.html' %}

{% block content %}
    <h2>Вы действительно хотите удалить {{ product.name }}?</h2>
    <form action="" method="POST">
    {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Да">
        <a href="{% url 'product_view' product.pk %}" class="btn btn-success">Нет</a>
    </form>
{% endblock %}

bishop/webapp/templates/product/product_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
    {% include 'partial/product_form.html' with button_text='Изменить' %}
    </form>
{% endblock %}

bishop/webapp/templates/product/product_view.html
{% extends 'base.html' %}

{% block content %}

    <div class="card">
        <h5 class="card-header">{{ product.name }}</h5>
        <div class="card-body">
            <p class="card-text">Цена: {{ product.price }}</p>
            <p class="card-text">Категория: <a href="{% url 'product_by_category' product.category %}">{{ product.get_category_display }}</a></p>
            <p class="card-text">Остаток: {{ product.balance }}</p>
            <p class="card-text">Описание товара: {{ product.description }}</p>
            <a href="{% url 'product_update' product.pk %}" class="btn btn-primary">Редактировать</a>
            <a href="{% url 'product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
        </div>
    </div>
{% endblock %}